TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: -0.2
  max_vel_theta: 0.4
  min_vel_theta: -0.4
  min_in_place_vel_theta: 0.6


  acc_lim_theta: 0.3
  acc_lim_x: 0.1
  acc_lim_y: 0.1

  holonomic_robot: false

  xy_goal_tolerance:  0.20
  yaw_goal_tolerance: 0.20

  sim_time: 1.0
  sim_granularity: 0.025
  vx_samples: 20
  vtheta_samples: 40

  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  occdist_scale: 0.01
  heading_lookahead: 0.325
  dwa: false

  oscillation_reset_dist: 0.05
  meter_scoring: true