local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 0.75
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05

  transform_tolerance: 3.0

  observation_sources: point_cloud_sensor

  # assuming receiving a cloud from rtabmap_ros/obstacles_detection node
  point_cloud_sensor: {
    sensor_frame: camera_link,
    data_type: PointCloud2, 
    topic: openni_points, 
    expected_update_rate: 2.5,
    marking: true, 
    clearing: true,
    min_obstacle_height: -99999.0,
    max_obstacle_height: 99999.0}

  # laser_scanner_sensor: {
  #   sensor_frame: base_laser,
  #   data_type: LaserScan, 
  #   topic: /rtabmap/scan, 
  #   expected_update_rate: 8.0,
  #   marking: true, 
  #   clearing: true}

