# CMake generated Testfile for 
# Source directory: /home/tej/Documents/AniClientCpp/json-nlohmann/test
# Build directory: /home/tej/Documents/AniClientCpp/json-nlohmann/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-algorithms_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-algorithms")
set_tests_properties(test-algorithms_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-algorithms_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-algorithms" "--no-skip")
set_tests_properties(test-algorithms_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-allocator_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-allocator")
set_tests_properties(test-allocator_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-allocator_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-allocator" "--no-skip")
set_tests_properties(test-allocator_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-alt-string_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-alt-string")
set_tests_properties(test-alt-string_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-alt-string_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-alt-string" "--no-skip")
set_tests_properties(test-alt-string_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-bson_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-bson")
set_tests_properties(test-bson_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-bson_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-bson" "--no-skip")
set_tests_properties(test-bson_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-capacity_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-capacity")
set_tests_properties(test-capacity_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-capacity_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-capacity" "--no-skip")
set_tests_properties(test-capacity_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-cbor_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-cbor")
set_tests_properties(test-cbor_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-cbor_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-cbor" "--no-skip")
set_tests_properties(test-cbor_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-class_const_iterator_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-class_const_iterator")
set_tests_properties(test-class_const_iterator_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-class_const_iterator_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-class_const_iterator" "--no-skip")
set_tests_properties(test-class_const_iterator_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-class_iterator_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-class_iterator")
set_tests_properties(test-class_iterator_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-class_iterator_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-class_iterator" "--no-skip")
set_tests_properties(test-class_iterator_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-class_lexer_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-class_lexer")
set_tests_properties(test-class_lexer_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-class_lexer_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-class_lexer" "--no-skip")
set_tests_properties(test-class_lexer_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-class_parser_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-class_parser")
set_tests_properties(test-class_parser_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-class_parser_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-class_parser" "--no-skip")
set_tests_properties(test-class_parser_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-comparison_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-comparison")
set_tests_properties(test-comparison_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-comparison_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-comparison" "--no-skip")
set_tests_properties(test-comparison_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-concepts_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-concepts")
set_tests_properties(test-concepts_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-concepts_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-concepts" "--no-skip")
set_tests_properties(test-concepts_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-constructor1_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-constructor1")
set_tests_properties(test-constructor1_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-constructor1_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-constructor1" "--no-skip")
set_tests_properties(test-constructor1_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-constructor2_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-constructor2")
set_tests_properties(test-constructor2_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-constructor2_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-constructor2" "--no-skip")
set_tests_properties(test-constructor2_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-convenience_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-convenience")
set_tests_properties(test-convenience_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-convenience_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-convenience" "--no-skip")
set_tests_properties(test-convenience_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-conversions_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-conversions")
set_tests_properties(test-conversions_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-conversions_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-conversions" "--no-skip")
set_tests_properties(test-conversions_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-deserialization_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-deserialization")
set_tests_properties(test-deserialization_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-deserialization_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-deserialization" "--no-skip")
set_tests_properties(test-deserialization_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-element_access1_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-element_access1")
set_tests_properties(test-element_access1_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-element_access1_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-element_access1" "--no-skip")
set_tests_properties(test-element_access1_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-element_access2_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-element_access2")
set_tests_properties(test-element_access2_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-element_access2_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-element_access2" "--no-skip")
set_tests_properties(test-element_access2_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-inspection_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-inspection")
set_tests_properties(test-inspection_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-inspection_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-inspection" "--no-skip")
set_tests_properties(test-inspection_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-items_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-items")
set_tests_properties(test-items_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-items_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-items" "--no-skip")
set_tests_properties(test-items_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-iterators1_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-iterators1")
set_tests_properties(test-iterators1_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-iterators1_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-iterators1" "--no-skip")
set_tests_properties(test-iterators1_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-iterators2_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-iterators2")
set_tests_properties(test-iterators2_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-iterators2_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-iterators2" "--no-skip")
set_tests_properties(test-iterators2_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-json_patch_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-json_patch")
set_tests_properties(test-json_patch_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-json_patch_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-json_patch" "--no-skip")
set_tests_properties(test-json_patch_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-json_pointer_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-json_pointer")
set_tests_properties(test-json_pointer_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-json_pointer_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-json_pointer" "--no-skip")
set_tests_properties(test-json_pointer_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-large_json_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-large_json")
set_tests_properties(test-large_json_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-large_json_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-large_json" "--no-skip")
set_tests_properties(test-large_json_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-merge_patch_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-merge_patch")
set_tests_properties(test-merge_patch_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-merge_patch_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-merge_patch" "--no-skip")
set_tests_properties(test-merge_patch_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-meta_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-meta")
set_tests_properties(test-meta_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-meta_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-meta" "--no-skip")
set_tests_properties(test-meta_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-modifiers_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-modifiers")
set_tests_properties(test-modifiers_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-modifiers_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-modifiers" "--no-skip")
set_tests_properties(test-modifiers_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-msgpack_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-msgpack")
set_tests_properties(test-msgpack_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-msgpack_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-msgpack" "--no-skip")
set_tests_properties(test-msgpack_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-noexcept_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-noexcept")
set_tests_properties(test-noexcept_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-noexcept_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-noexcept" "--no-skip")
set_tests_properties(test-noexcept_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-pointer_access_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-pointer_access")
set_tests_properties(test-pointer_access_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-pointer_access_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-pointer_access" "--no-skip")
set_tests_properties(test-pointer_access_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-readme_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-readme")
set_tests_properties(test-readme_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-readme_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-readme" "--no-skip")
set_tests_properties(test-readme_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-reference_access_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-reference_access")
set_tests_properties(test-reference_access_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-reference_access_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-reference_access" "--no-skip")
set_tests_properties(test-reference_access_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-regression_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-regression")
set_tests_properties(test-regression_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-regression_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-regression" "--no-skip")
set_tests_properties(test-regression_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-serialization_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-serialization")
set_tests_properties(test-serialization_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-serialization_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-serialization" "--no-skip")
set_tests_properties(test-serialization_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-testsuites_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-testsuites")
set_tests_properties(test-testsuites_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-testsuites_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-testsuites" "--no-skip")
set_tests_properties(test-testsuites_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-to_chars_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-to_chars")
set_tests_properties(test-to_chars_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-to_chars_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-to_chars" "--no-skip")
set_tests_properties(test-to_chars_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-ubjson_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-ubjson")
set_tests_properties(test-ubjson_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-ubjson_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-ubjson" "--no-skip")
set_tests_properties(test-ubjson_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-udt_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-udt")
set_tests_properties(test-udt_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-udt_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-udt" "--no-skip")
set_tests_properties(test-udt_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-unicode_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-unicode")
set_tests_properties(test-unicode_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-unicode_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-unicode" "--no-skip")
set_tests_properties(test-unicode_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-wstring_default "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-wstring")
set_tests_properties(test-wstring_default PROPERTIES  LABELS "default" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
add_test(test-wstring_all "/home/tej/Documents/AniClientCpp/json-nlohmann/test/test-wstring" "--no-skip")
set_tests_properties(test-wstring_all PROPERTIES  LABELS "all" WORKING_DIRECTORY "/home/tej/Documents/AniClientCpp")
subdirs("cmake_import")
subdirs("cmake_import_minver")
subdirs("cmake_add_subdirectory")
